### ISSUE TITLE
Unable to build project after installation of nativescript-websockets

### ISSUE THREAD

**Issue by benjaminpaul** [NathanaelA/nativescript-websockets#7] opened 2016-01-14 15:05 UTC
Hi There!

I have attempted to install "nativescript-websockets" into my application as per your instructions however since doing that I am no longer able to build my project.

Here is the output when I attempt to build...

=== BUILD TARGET PocketSocket OF PROJECT Pods WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
write-file /Users/ben.paul/Library/Developer/Xcode/DerivedData/jegroupordering-aqqlxkvizbcvkwfnosywwqxrtbby/Build/Intermediates/Pods.build/all-product-headers.yaml

=== BUILD TARGET Pods OF PROJECT Pods WITH CONFIGURATION Debug ===

Check dependencies

=== BUILD TARGET jegroupordering OF PROJECT jegroupordering WITH CONFIGURATION Debug ===

Check dependencies
CodeSign error: entitlements are required for product type 'Application' in SDK 'Simulator - iOS 9.2'. Your Xcode installation may be damaged.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Command xcodebuild failed with exit code 65
# build ios
┌─────────┬────────────────────────────────────────────────────────────────────┐
│ Usage   │ Synopsis                                                           │
│ General │ $ tns build ios [--for-device] [--release] [--copy-to <File Path>] │
└─────────┴────────────────────────────────────────────────────────────────────┘

Builds the project for iOS and produces an APP or IPA that you can manually deploy in the iOS Simulator or on device, respectively.

IMPORTANT: Before building for iOS device, verify that you have configured a valid pair of certificate and provisioning profile on your OS X system. 

### Options

    * --release - If set, produces a release build. Otherwise, produces a debug build.
    * --for-device - If set, produces an application package that you can deploy on device. Otherwise, produces a build that you can run only in the native iOS Simulator.
    * --copy-to - Specifies the file path where the built .ipa will be copied. If it points to a non-existent directory, it will be created. If the specified value is directory, the original file name will be used.

Any idea what may be causing this?

**Comment by NathanaelA** [comment] 2016-01-14 19:19
Yeah, the latest version of XCode has issues.  The easiest solution is to downgrade to the prior version of XCode.     You can also build release versions of the app; to mitigate the issue; but basically XCode thinks the test version needs to be signed.

**Comment by alg** [comment] 2016-01-26 12:41
@NathanaelA any idea why it happens only after installing the plugin?

**Comment by NathanaelA** [comment] 2016-01-26 16:18
Yes.   The issue is because XCode 7.2 has an issue when it builds projects with any Cocoapods. When you add a Cocoapod; the compilation step is different in the way it builds the application.  And then for some reason it thinks it needs to sign the app; which isn't valid for the emulator, so it crashes.    This is actually an issue in general, not only NativeScript.  I've seen the error popup in several different iPhone communities.

**Comment by alg** [comment] 2016-01-26 16:52
Yup, I see them all over the web. Does it make sense to have a branch with non-Pod setup? It kind of ruins whole {N} development experience if I have to build releases instead of livesync all the time. :)

**Comment by NathanaelA** [comment] 2016-01-26 16:58
https://github.com/NativeScript/ios-runtime/issues/488 I believe is the primary issue.
Also If you downgrade to XCode 7.1 you won't have this issue anymore.

**Comment by alg** [comment] 2016-01-26 17:01
Well, downgrading may not be an option for me at this point. We use the latest XCode for another project. What about non-Pod setup? I had an impression that you transferred it to Pod just recently. Is it possible to use it without Pod at all?

**Comment by NathanaelA** [comment] 2016-01-26 17:14
Yes, it is -- the prior version of websockets used a compiled library that was included and then you had to make a change to the project file to include it.  But it worked.   If you get v1.01 it was the last non-pod file version.  The doc file that comes with the npm will describe how to install it.

**Comment by alg** [comment] 2016-01-26 18:31
Thanks, I'm using 1.0.1 now and it all builds, however I'm getting a strange error (which I also noticed in your blog comments unanswered btw):

```Jan 26 21:28:22 sunray mobile[2329]: file:///app/tns_modules/nativescript-websockets/websockets.js:65:36: JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate```

Also, in the steps you instruct on adding LibSystem.dynlib, but I wasn't able to locate it. May it be the reason?

**Comment by NathanaelA** [comment] 2016-01-26 19:06
I suspect that is why; but I don't know for sure -- since I switched to using Cocoapods because of the issues with iOS 9 with the compiled lib, and switching to a cocoapod simplified everything.

**Comment by nassimus26** [comment] 2016-02-07 23:23
i am facing the same issue, any solution ?

**Comment by NathanaelA** [comment] 2016-02-08 00:19
Actually there is now a fix for using  xcode 7.2+ with CocoaPods.  It is shipping in the next version of NativeScript but I can walk you through the fix if you need it right now.

**Comment by NathanaelA** [comment] 2016-02-11 23:01
Look what I got for you guys!    Here is the fix so that you can continue using xCode 7.2 and Cocoapods.  http://fluentreports.com/blog/?p=214

**Closed by NathanaelA** 2016-02-11 23:01 UTC
